### ISSUE TITLE
HelloWorld, undefined reference to `start64'

### ISSUE THREAD

**Issue by milisarge** [torokernel/torokernel#400]
```
# ../CloudIt.sh HelloWorld
ld may not work (see issue#312)
Free Pascal Compiler version 3.0.4 [2020/05/08] for x86_64
Copyright (c) 1993-2017 by Florian Klaempfl and others
Target OS: Linux for x86-64
Compiling HelloWorld.pas
Compiling /opt/torokernel/rtl/system.pas
Compiling /opt/torokernel/rtl/fpintres.pp
Compiling /opt/torokernel/rtl/objpas.pas
Compiling /opt/torokernel/rtl/SysUtils.pas
Compiling ../../rtl/Kernel.pas
Compiling ../../rtl/Arch.pas
Compiling ../../rtl/drivers/Console.pas
Compiling ../../rtl/Process.pas
Compiling ../../rtl/drivers/Console.pas
Compiling ../../rtl/Memory.pas
Compiling /opt/torokernel/rtl/lnfodwrfToro.pas
Compiling ../../rtl/Filesystem.pas
Compiling /opt/torokernel/rtl/Network.pas
Compiling ../../rtl/Debug.pas
Compiling ../../rtl/drivers/Pci.pas
Closing script ppas.sh
18376 lines compiled, 0.3 sec
ld: kernel64.o: in function `init_paging2M1':
multiboot.s:(.text:+0xf9): undefined reference to `start64'
qemu.args=-m 16 -smp 1 -nographic -device isa-debug-exit,iobase=0xf4,iosize=0x04
Press Ctrl-a x to exit emulator
qemu: could not load kernel 'HelloWorld.bin': No such file or directory
```
any idea?

**Comment by MatiasVara** [comment]
Hello, the HelloWorld.bin is not generated. The second line tells you that linking with that version of ld does not work (see #312). I am currently using `GNU ld (GNU Binutils) 2.26.1`.

**Comment by milisarge** [comment]
yes i have 2.32, how can i help for this issue?

**Comment by MatiasVara** [comment]
I am not really sure why ld 2.32 does not work. All that I know is in #312. For the moment, I would recommend using 2.26.1. This script will be removed soon. I am removing the support for multiboot so those python scripts will not needed anymore.

**Comment by milisarge** [comment]
how can i disable multiboot?

**Comment by MatiasVara** [comment]
Can you elaborate? What do you want to do?

**Comment by milisarge** [comment]
i am trying to link with ld 2.32 without multiboot according to this issue 
https://github.com/torokernel/torokernel/issues/312

**Comment by MatiasVara** [comment]
You have two options: 
1) You can get 2.26.1 and compile it. 
2) You can use the builder to build a ".img" and then boot toro without a multiboot kernel. To do this, you have to first compile "fpc builder/build.pas" and then compile an example by doing "../CloudIt.sh HelloWorld "" "img".

**Comment by milisarge** [comment]
i tried second option but still gives me same error
```
# LC_ALL=C fpc builder/build.pas 
Free Pascal Compiler version 3.0.4 [2020/05/08] for x86_64
Copyright (c) 1993-2017 by Florian Klaempfl and others
Target OS: Linux for x86-64
Compiling builder/build.pas
Linking builder/build
/bin/ld: warning: link.res contains output sections; did you forget -T?
66 lines compiled, 0.2 sec

```
```
../CloudIt.sh HelloWorld "" "img"
ld may not work (see issue#312)
Free Pascal Compiler version 3.0.4 [2020/05/08] for x86_64
Copyright (c) 1993-2017 by Florian Klaempfl and others
Target OS: Linux for x86-64
Compiling HelloWorld.pas
Compiling /opt/unikernel/torokernel/rtl/system.pas
Compiling /opt/unikernel/torokernel/rtl/fpintres.pp
Compiling /opt/unikernel/torokernel/rtl/objpas.pas
Compiling /opt/unikernel/torokernel/rtl/SysUtils.pas
Compiling ../../rtl/Kernel.pas
Compiling ../../rtl/Arch.pas
Compiling ../../rtl/drivers/Console.pas
Compiling ../../rtl/Process.pas
Compiling ../../rtl/drivers/Console.pas
Compiling ../../rtl/Memory.pas
Compiling /opt/unikernel/torokernel/rtl/lnfodwrfToro.pas
Compiling ../../rtl/Filesystem.pas
Compiling /opt/unikernel/torokernel/rtl/Network.pas
Compiling ../../rtl/Debug.pas
Compiling ../../rtl/drivers/Pci.pas
Closing script ppas.sh
18376 lines compiled, 0.3 sec
ld: kernel64.o: in function `init_paging2M1':
multiboot.s:(.text:+0xf9): undefined reference to `start64'
qemu.args=-m 16 -smp 1 -nographic -device isa-debug-exit,iobase=0xf4,iosize=0x04
Press Ctrl-a x to exit emulator
qemu-system-x86_64: img: Could not open 'img': No such file or directory
```

**Comment by MatiasVara** [comment]
`../CloudIt.sh HelloWorld "" "" "img"`

**Comment by milisarge** [comment]
ok it worked at now, but qemu uses %25 of cpu, is it normal or because of forever loop ?

**Comment by MatiasVara** [comment]
I tried in mine and toro is rebooting. Did you get the "HelloWorld"?

**Comment by MatiasVara** [comment]
After the HelloWorld, toro halts the current core so the cpu usage should go to 0%.

**Comment by MatiasVara** [comment]
I am afraid the bug is also there when you use an "img". The only option is to compile with ld 2.26.1

**Comment by milisarge** [comment]
no i couldt get , 
![g](https://user-images.githubusercontent.com/15840648/81865514-af6c2080-9576-11ea-817a-c6f2356697f9.png)
